parameters:
  - name: codebase
    type: string
  - name: action
    type: string
  - name: service_principal_identifier
    type: string
  - name: component
    type: string
  - name: log_level
    type: string
  - name: pool_type
    type: string
  - name: environment
    type: string
    default: ''

stages:
  - stage: 'Validate_${{ parameters.component }}'
    displayName: 'Validate - ${{ parameters.component }}'
    variables:
      - template: env-np.yml
    ${{ if eq(parameters.pool_type, 'MS_Hosted')) }}:
      pool:
        vmImage: 'ubuntu-latest'
    ${{ else }}:
      pool: ${{ variables.agentPool }}
    jobs:
      - template: validate.yml
        parameters:
          terragrunt_codebase: ${{ parameters.terragrunt_codebase }}
          service_principal_identifier: ${{ parameters.service_principal_identifier }}
          pool_type: ${{ parameters.pool_type }}
          terragrunt_log_level: ${{ parameters.terragrunt_log_level }}
          component: ${{ parameters.component }}
          buildSourceBranch: ${{ variables.buildSourceBranch }}
          skipTrufflehogScan: ${{ parameters.skipTrufflehogScan }}
          includeFoldersForTrufflehogScan: ${{ parameters.includeFoldersForTrufflehogScan }}
          excludeFoldersForTrufflehogScan: ${{ parameters.excludeFoldersForTrufflehogScan }}
          environment : ${{parameters.environment}}
