parameters:
  - name: codebase
    type: string
  - name: action
    type: string
  - name: service_principal_identifier
    type: string
  - name: component
    type: string
  - name: log_level
    type: string
  - name: pool_type
    type: string
  - name: environment
    type: string
    default: ''

stages:
  - stage: 'Validate_${{ parameters.component }}'
    displayName: 'Validate - ${{ parameters.component }}'
    variables:
      - template: env-dev-config.yml
    ${{ if eq(parameters.pool_type, 'MS_Hosted') }}:
      pool:
        vmImage: 'ubuntu-latest'
    ${{ else }}:
      pool: ${{ variables.agentPool }}
    jobs:
      - template: ./stages-templates/validate.yml
        parameters:
          codebase: ${{ parameters.codebase }}
          service_principal_identifier: ${{ parameters.service_principal_identifier }}
          pool_type: ${{ parameters.pool_type }}
          log_level: ${{ parameters.log_level }}
          component: ${{ parameters.component }}
          buildSourceBranch: ${{ variables.buildSourceBranch }}
          environment : ${{parameters.environment}}

  - stage: 'Plan_${{ parameters.component }}'
    displayName: 'Plan - ${{ parameters.component }}'
    variables:
      - template: env-dev-config.yml
    ${{ if eq(parameters.pool_type, 'MS_Hosted') }}:
      pool:
        vmImage: 'ubuntu-latest'
    ${{ else }}:
      pool: ${{ variables.agentPool }}
    jobs:
      - template: ./stages-templates/plan.yml
        parameters:
          codebase: ${{ parameters.codebase }}
          service_principal_identifier: ${{ parameters.service_principal_identifier }}
          ${{ if eq(parameters.action, 'Deploy') }}:
            plan_type: ''
          ${{ if eq(parameters.action, 'Destroy') }}:
            plan_type: '-destroy'
          pool_type: ${{ parameters.pool_type }}
          log_level: ${{ parameters.terragrunt_log_level }}
          component: ${{ parameters.component }}
          environment : ${{parameters.environment}}