parameters:
- name: codebase
  type: string
- name: service_principal_identifier
  type: string
- name: pool_type
  type: string
- name: log_level
  type: string
- name: component
  type: string
- name: buildSourceBranch
  type: string
- name: environment
  type: string
  default: ''

jobs:
- job: Validate
  steps:
  - ${{ if eq(parameters.component, 'NONE') }}:
    - task: Bash@3
      displayName: Environment is not selected
      continueOnError: false
      inputs:
        targetType: 'inline'
        failOnStderr: true
        script: |
          exit 1
  - template: ./agent-config.yml
    parameters:
      pool_type: ${{ parameters.pool_type }}
      component: ${{ parameters.component }}
      environment: ${{parameters.environment}}
  - template: ./print-env-variables.yml
    parameters:
      buildSourceBranch: ${{ parameters.buildSourceBranch }}

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: '/usr/local/bin/terragrunt validate'
      workingDirectory: '$(Build.SourcesDirectory)/${{ parameters.codebase }}'
    displayName: 'Terragrunt Validate'
    env:
      ARM_CLIENT_SECRET: $(${{ parameters.service_principal_identifier }}_CLIENT_SECRET)
      ARM_CLIENT_ID: $(${{ parameters.service_principal_identifier }}_CLIENT_ID)
      ARM_SUBSCRIPTION_ID: $(${{ parameters.service_principal_identifier }}_SUBSCRIPTION_ID)
      LOG_LEVEL: ${{ parameters.log_level }}
  - template: ./cleanup.yml